In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([10, 10, 10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [4]:
tensor = tf.constant([[[10, 9, 8, 8, 9],
                     [10, 9, 8, 8, 9],
                      [10, 9, 8, 8, 9]],
                      [[10, 9, 8, 8, 9],
                     [10, 9, 8, 8, 9],
                      [10, 9, 8, 8, 9]]])
tensor

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[10,  9,  8,  8,  9],
        [10,  9,  8,  8,  9],
        [10,  9,  8,  8,  9]],

       [[10,  9,  8,  8,  9],
        [10,  9,  8,  8,  9],
        [10,  9,  8,  8,  9]]], dtype=int32)>

In [5]:
tensor.ndim

3

In [6]:
float_matrix = tf.constant([[10., 10.],[10., 10.]], dtype = tf.float16)
float_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10., 10.],
       [10., 10.]], dtype=float16)>

In [7]:
float_matrix.ndim

2

what we've created so far:
- scalar : a single number
- vector : a number with direcction(e.g. wind speed and direction)
- matrix : a 2-dimentional array of numbers
- tensor : a n-dimentional array of numbers(when n can be any number, a 0-dimentional tensor is a scalar, a 1-dimentional tensor is a vector)


### creating tensors with tf.variable

In [8]:
changeable_tensor = tf.Variable([[10, 8],
                                [10, 8]])
unchangeable_tensor = tf.constant([[10, 8],
                                [10, 8]])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[10,  8],
        [10,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  8],
        [10,  8]], dtype=int32)>)

In [9]:
changeable_tensor[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 5,  5],
       [10,  8]], dtype=int32)>

In [10]:
unchangeable_tensor[0].assign(5)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Random tensors

Random tensor are tensors of some abitrary size which contain random numbers

In [11]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [12]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [13]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [14]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape = (3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [15]:
shuffle = tf.random.shuffle(random_3)
random_3, shuffle

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193765, -1.8107855 ],
        [ 0.07595026, -1.2573844 ],
        [-0.7565803 , -0.06854702]], dtype=float32)>)

In [16]:
random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.uniform(shape = (3, 2))
shuffle_2 = tf.random.shuffle(random_4)
random_4, shuffle_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.1889317 , 0.52027524],
        [0.7493447 , 0.73561966],
        [0.45230794, 0.49039817]], dtype=float32)>)

In [17]:
tf.random.set_seed(42)
not_shuffled = tf.Variable([[10, 7],
                            [3, 4],
                            [1, 2]])
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled, shuffled

(<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 1,  2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 1,  2],
        [10,  7]], dtype=int32)>)

In [18]:
shuffled.ndim

2

In [19]:
tf.random.set_seed(42)
not_shuffled = tf.constant([10, 2, 3, 4])
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled, shuffled

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10,  2,  3,  4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4, 10,  2,  3], dtype=int32)>)

In [20]:
tensor = tf.constant([[[10, 2, 3],
                       [10, 2, 4],
                       [10, 3, 5]],
                      [[10, 4, 5],
                      [10, 6, 4],
                      [10, 2, 0]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[10,  2,  3],
        [10,  2,  4],
        [10,  3,  5]],

       [[10,  4,  5],
        [10,  6,  4],
        [10,  2,  0]]], dtype=int32)>

it looked like if we want our shuffled tensors to be in the same order we got to use the golobal level random seed and operation level radnom seed


In [21]:
tf.ones([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [23]:
# you can also tirn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A
# x = tf.constant(some_matrix)
# y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(numpy_A, shape = (2, 6, 2))
A

<tf.Tensor: shape=(2, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [25]:
numpy_A.shape

(24,)

In [26]:
tf.zeros(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Getting information from tensors

when dealing with tensors you probably want to be aware of the following attributes



* shape
* rank
* axis or dim
* size

In [27]:
rank_4_tensors = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensors[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
rank_4_tensors.shape, rank_4_tensors.ndim, tf.size(rank_4_tensors)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
print("Datatype of every element:", rank_4_tensors.dtype)
print("Number of dimensions (rank):", rank_4_tensors.ndim)
print("Shape of tensor:", rank_4_tensors.shape)
print("Elements along the 0 axis :", rank_4_tensors.shape[0])
print("Elements alont the last axis:", rank_4_tensors.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensors))

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis : 2
Elements alont the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [31]:
rank_4_tensors[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensors[:1, :1, :1, :5]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_2_tensor = tf.constant([[10, 8],
                             [3, 5]])
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 5], dtype=int32)>

In [34]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 8]],
 
        [[ 3],
         [ 5]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 8]],
 
        [[ 3],
         [ 5]]], dtype=int32)>)

In [35]:
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 8]],

       [[ 3],
        [ 5]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor, axis = 0), rank_2_tensor

(<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[10,  8],
         [ 3,  5]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  8],
        [ 3,  5]], dtype=int32)>)

### TensorOPS

In [37]:
tensor = tf.constant([[10, 8], [3, 4]])

In [38]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  80],
       [ 30,  40]], dtype=int32)>

In [39]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 18],
       [13, 14]], dtype=int32)>

In [40]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -2],
       [-7, -6]], dtype=int32)>

In [41]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  80],
       [ 30,  40]], dtype=int32)>

In [42]:
tf.add(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 28],
       [23, 24]], dtype=int32)>

In [43]:
tf.matmul(tensor, tensor, adjoint_a = True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[109,  92],
       [ 92,  80]], dtype=int32)>

In [44]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [45]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [46]:
A = tf.constant([[1, 2, 5],
                      [7, 2, 1],
                      [3, 3, 3]])
B = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])
A, B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [47]:
A@B, tf.matmul(A, B)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]], dtype=int32)>)

In [48]:
tf.reshape(B, shape = (2, 3))@B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 45,  98],
       [ 35, 106]], dtype=int32)>

In [49]:
tf.matmul(B, tf.reshape(B, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [50]:
B@tf.reshape(B, shape = (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [51]:
tf.transpose(B) @ A

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]], dtype=int32)>

Matrix multiplication is also referred to as the dot product

In [52]:
A, B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [53]:
tf.tensordot(A, B, axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [54]:
A.shape, B.shape

(TensorShape([3, 3]), TensorShape([3, 2]))

In [55]:
tf.matmul(A, tf.transpose(tf.reshape(B, shape = (2, 3))))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[43, 49],
       [37, 59],
       [42, 48]], dtype=int32)>

In [56]:
 C = tf.constant([10., 1.])
 D = tf.constant([10, 1])
 C, D, C.dtype, D.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  1.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  1], dtype=int32)>,
 tf.float32,
 tf.int32)

In [57]:
new_B = tf.cast(B, dtype = tf.float16)
B, new_B

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[3., 5.],
        [6., 7.],
        [1., 8.]], dtype=float16)>)

## Aggregating tensors

In [58]:
exp = tf.Variable([[10, 8],
                   [9, 10]])
exp_1 = exp[0, 0].assign(11)
exp, exp_1

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[11,  8],
        [ 9, 10]], dtype=int32)>,
 <tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
 array([[11,  8],
        [ 9, 10]], dtype=int32)>)

In [59]:
# aggregating tensors = compressing big chunks of data in a small single unit or so

In [60]:
non_abs = tf.constant([-10, -8])
tf.abs(non_abs)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>

forms of aggregation:
* minimum
* maximum
* mean
* sum of tensor

In [61]:
tensor = tf.constant([[112, 492, 10],
                      [45, 22, 90],
                      [1000, 3, 0]])
tf.reduce_mean(tensor), tf.reduce_min(tensor), tf.reduce_max(tensor), tf.reduce_sum(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=197>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1000>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1774>)

In [62]:
E = tf.constant(np.random.randint(0, 100, size = 50))

In [63]:
E, E.shape, tf.size(E)

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([63, 32,  6, 63,  8, 62, 53, 19, 27, 88, 39, 36, 98, 91, 37, 85, 41,
        31, 78, 29, 38, 42,  5, 21, 88, 87, 53, 75, 47, 27,  3,  8, 38, 93,
        90, 84, 81,  0, 23, 10, 34, 45, 79, 55,  8, 94, 96, 85, 33, 43])>,
 TensorShape([50]),
 <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [64]:
tf.cast(E, dtype = tf.float32)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([63., 32.,  6., 63.,  8., 62., 53., 19., 27., 88., 39., 36., 98.,
       91., 37., 85., 41., 31., 78., 29., 38., 42.,  5., 21., 88., 87.,
       53., 75., 47., 27.,  3.,  8., 38., 93., 90., 84., 81.,  0., 23.,
       10., 34., 45., 79., 55.,  8., 94., 96., 85., 33., 43.],
      dtype=float32)>

In [65]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float32)), tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))


(<tf.Tensor: shape=(), dtype=float32, numpy=29.96403694152832>,
 <tf.Tensor: shape=(), dtype=float32, numpy=897.8435668945312>)

In [66]:
## positional maximum and minimum
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
F = tensor

In [67]:
F[tf.argmax(tensor)], F[tf.argmin(tensor)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>)

In [68]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [69]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [70]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

## Squeezing a tensor

In [71]:
G = tf.constant(tf.random.uniform(shape = [50]), shape=[1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [72]:
G.ndim

5

In [73]:
print(tf.rank(G)), G.shape

tf.Tensor(5, shape=(), dtype=int32)


(None, TensorShape([1, 1, 1, 1, 50]))

In [74]:
G_squeezed = tf.squeeze(G, axis = 2)
G_squeezed

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
          0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
          0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
          0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
          0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
          0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
          0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
          0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
          0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
          0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]],
      dtype=float32)>

In [75]:
G_squeezed.shape, G_squeezed.ndim, G.shape, G.ndim

(TensorShape([1, 1, 1, 50]), 4, TensorShape([1, 1, 1, 1, 50]), 5)

### one Hot Encoding

In [76]:
import random
tf.random.set_seed(42)
some_list = [random.randint(0, 10) for i in range(10)]
some_list

[9, 10, 9, 0, 0, 6, 9, 6, 9, 2]

In [77]:
tf.one_hot(some_list, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [78]:
tf.one_hot(some_list, depth = 10, on_value = "hi", off_value = "bye")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye', b'hi'],
       [b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye', b'bye'],
       [b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye', b'hi'],
       [b'hi', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye', b'bye'],
       [b'hi', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye', b'bye'],
       [b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'hi', b'bye',
        b'bye', b'bye'],
       [b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye', b'hi'],
       [b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'hi', b'bye',
        b'bye', b'bye'],
       [b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye', b'hi'],
       [b'bye', b'bye', b'hi', b'bye', b'bye', b'bye', b'bye', b'bye',
        b'bye',

In [79]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [80]:
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [81]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [82]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [83]:
!nvidia-smi

Tue Apr 14 05:27:56 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P0             27W /   70W |     109MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----